language: java
sudo: false

# avoid double builds on pull requests
branches:
  only:
    master

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# caches for build artifacts
cache:
  directories:
    - ~/travis_cache

matrix:
  include:
    # build cache
    - stage: Build cache
      script:
        - mv ~/travis_cache ~/travis_cache_old
        - mkdir ~/travis_cache
        - echo "$TRAVIS_BUILD_ID" > ~/travis_cache/travis_build_id

    # build + test
    - stage: Build + test
      jdk: oraclejdk8
      os: linux
      dist: trusty
      after_success:
        - cp phoenicis-dist/target/*.deb ~/travis_cache/
    - stage: Build + test
      jdk: oraclejdk9
      os: linux
      dist: trusty
    - stage: Build + test
      os: osx
      osx_image: xcode9.2

    # Check the format
    - stage: Check format
      jdk: oraclejdk8
      os: linux
      dist: trusty
      # do not use default install (runs formatter)
      install: true
      script:
        - mvn -Pcheck-formatted validate formatter:validate

    # Check installations
    - stage: Check installations
      os: linux
      dist: trusty
      script:
        # check that cache has been filled in current build
        - if test "$TRAVIS_BUILD_ID" != `cat ~/travis_cache/travis_build_id`; then travis_terminate 1; fi
        - rm -f ~/travis_cache/travis_build_id
        - sudo dpkg -i ~/travis_cache/*.deb && sudo apt install -fy
        - mv ~/travis_cache ~/travis_cache_old
        - mkdir ~/travis_cache # clear the cache

    # Check GitHub Pages
    - stage: Check GitHub Pages
      os: linux
      language: ruby
      rvm:
        - 2.5
      before_install: cd docs
      script:
        - bundle exec jekyll build
        - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --assume-extension
