language: java
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

matrix:
  include:
    # The normal tests
    - jdk: oraclejdk8
      os: linux
      dist: trusty
    - jdk: oraclejdk9
      os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.2

    # Check the format
    - stage: Check format
      jdk: oraclejdk8
      os: linux
      dist: trusty
      script:
      - mvn test -B
      - ./check_formatted.sh

    # Check GitHub Pages
    - stage: Check GitHub Pages
      os: linux
      language: ruby
      rvm:
        - 2.1
      install:
        - gem install jekyll
        - gem install html-proofer
        - gem install jekyll-remote-theme
        - gem install github-pages
        - gem install tzinfo-data
      before_script: cd docs
      script:
        - bundle exec jekyll build
        - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
