language: java

# avoid double builds on pull requests
branches:
  only:
    master

jobs:
  include:
    # Check format
    - stage: Basics
      name: Check format
      # do not use default install (runs formatter)
      install: true
      script: mvn -Pcheck-formatted validate formatter:validate

    # build + test
    - stage: Build + test
      name: Linux OpenJDK 8
      os: linux
      dist: trusty
      jdk: openjdk8
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name ubuntu-18-04 openjdk:8 tail -f /dev/null
      install:
        - docker exec -t ubuntu-18-04 bash -c "apt -qq update;
                                               apt install -y git;
                                               apt install -y maven;
                                               apt install -y openjfx;
                                               apt install -y gettext"
      script:
        - docker exec -t ubuntu-18-04 bash -c "cd /travis;
                                               git clone https://github.com/PhoenicisOrg/phoenicis.git;
                                               cd phoenicis;
                                               mvn -B clean package"

    # build + test
    - stage: Build + test
      name: Linux Oracle JDK 8
      os: linux
      dist: trusty
      jdk: oraclejdk8
    - stage: Build + test
      name: Linux OpenJDK 10
      os: linux
      dist: trusty
      jdk: openjdk10
      script: mvn clean package
    - stage: Build + test
      name: Linux OpenJDK 11
      os: linux
      dist: trusty
      jdk: openjdk11
    - stage: Build + test
      name: Linux Oracle JDK 11
      os: linux
      dist: trusty
      jdk: oraclejdk11
    - stage: Build + test
      name: OSX XCode 9.2
      os: osx
      osx_image: xcode9.2

    # Build + test packages
    - stage: Packages
      name: Flatpak
      os: linux
      dist: trusty
      jdk: openjdk11
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y flatpak-builder
      after_script:
        - cd phoenicis-dist/src/flatpak/
        - flatpak-builder build-dir org.phoenicis.javafx.json --force-clean
    - stage: Packages
      name: deb
      os: linux
      dist: trusty
      jdk: openjdk11
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name ubuntu-18-04 openjdk:8 tail -f /dev/null
      install:
        - docker exec -t ubuntu-18-04 bash -c "dpkg --add-architecture i386;
                                               apt -qq update;
                                               apt install -y git;
                                               apt install -y maven;
                                               apt install -y gettext"
      script:
        - docker exec -t ubuntu-18-04 bash -c "cd /travis;
                                               git clone https://github.com/PhoenicisOrg/phoenicis.git;
                                               cd phoenicis;
                                               mvn -B clean package;
                                               cd phoenicis-dist/target/;
                                               dpkg -R -i ./;
                                               apt install -fy"
    - stage: Packages
      name: dmg
      os: osx
      osx_image: xcode9.3
      after_script:
        - mvn clean install
        - cd phoenicis-dist/target/
        - mvn jfx:native

    # Check GitHub Pages
    - stage: Check GitHub Pages
      env: NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
      language: ruby
      rvm:
        - 2.5
      before_install: cd docs
      script:
        - bundle exec jekyll build
        - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --assume-extension
