language: java
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

matrix:
  include:
    # The normal tests
    - jdk: oraclejdk8
      os: linux
      dist: trusty
    - jdk: oraclejdk9
      os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.2
        
    # Check the format
    - stage: Check format
      jdk: oraclejdk8
      os: linux
      dist: trusty
      # do not use default install (runs formatter)
      install: true
      script:
        - mvn -Pcheck-formatted validate formatter:validate
