language: java
sudo: false

# avoid double builds on pull requests
branches:
  only:
    master

jobs:
  include:
    # Check format
    - stage: Check format
      # do not use default install (runs formatter)
      install: true
      script: mvn -Pcheck-formatted validate formatter:validate

    # build + test
    - stage: Build + test
      os: linux
      dist: trusty
      jdk: openjdk8
    # build + test
    - stage: Build + test
      os: linux
      dist: trusty
      jdk: openjdk8
      addons:
        apt:
          packages: oracle-java8-installer
    - stage: Build + test
      os: linux
      dist: trusty
      jdk: oraclejdk9
      addons:
        apt:
          packages: oracle-java9-installer
    - stage: Build + test
      os: osx
      osx_image: xcode9.2

    # Check GitHub Pages
    - stage: Check GitHub Pages
      env: NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
      language: ruby
      rvm:
        - 2.5
      before_install: cd docs
      script:
        - bundle exec jekyll build
        - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --assume-extension
