language: java
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

matrix:
  include:
    - jdk: oraclejdk8
      os: linux
      dist: trusty
    - jdk: oraclejdk9
      os: linux
      dist: trusty
    - jdk: openjdk8
      os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.2