language: java
sudo: false

# avoid double builds on pull requests
branches:
  only:
    master

jobs:
  include:
    # Check format
    - stage: Check format
      # do not use default install (runs formatter)
      install: true
      script: mvn -Pcheck-formatted validate formatter:validate

    # build + test
    - stage: Build + test
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name ubuntu-16-04 -v $(pwd):/travis ubuntu:16.04 tail -f /dev/null
      install:
        - docker exec -t ubuntu-16-04 bash -c "apt-get -qq update;
                                               apt-get install -y git;
                                               apt-get install -y maven"
      script:
        - docker exec -t ubuntu-16-04 bash -c "cd /travis;
          export JAVA_HOME=\"/usr/lib/jvm/java-8-openjdk-amd64\";
          git clone https://github.com/PhoenicisOrg/phoenicis.git;
          cd phoenicis;
          mvn test -B"
    # build + test
    - stage: Build + test
      os: linux
      dist: trusty
      jdk: oraclejdk8
      addons:
        apt:
          packages: oracle-java8-installer
    - stage: Build + test
      os: linux
      dist: trusty
      jdk: oraclejdk9
      addons:
        apt:
          packages: oracle-java9-installer
    - stage: Build + test
      os: osx
      osx_image: xcode9.2

    # Check GitHub Pages
    - stage: Check GitHub Pages
      env: NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
      language: ruby
      rvm:
        - 2.5
      before_install: cd docs
      script:
        - bundle exec jekyll build
        - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --assume-extension
