language: java
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

before_install:
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers and https://github.com/SublimeText/UnitTesting/issues/74
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
      fi

matrix:
  include:
    # The normal tests
    - jdk: oraclejdk8
      os: linux
      dist: trusty
    - jdk: oraclejdk9
      os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.2

    # Check the format
    - stage: Check format
      jdk: oraclejdk8
      os: linux
      dist: trusty
      script:
      - mvn test -B
      - ./check_formatted.sh