language: java
sudo: true # must have same "sudo" state in stages for caching

# avoid double builds on pull requests
branches:
  only:
    master

# caches for build artifacts
cache:
  directories:
    - $HOME/travis_cache

jobs:
  include:
    # build cache
    - stage: Basics
      name: Build cache
      os: linux
      dist: trusty
      jdk: openjdk8
      sudo: required
      install: true
      script:
        - mv $HOME/travis_cache $HOME/travis_cache_old
        - mkdir $HOME/travis_cache
        - echo "$TRAVIS_BUILD_ID" > $HOME/travis_cache/travis_build_id

    # Check format
    - stage: Basics
      name: Check format
      # do not use default install (runs formatter)
      install: true
      script: mvn -Pcheck-formatted validate formatter:validate

    # build + test
    - stage: Build + test
      name: Linux OpenJDK 8
      os: linux
      dist: trusty
      jdk: openjdk8
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name ubuntu-16-04 -v $HOME:/travis openjdk:8 tail -f /dev/null
      install:
        - docker exec -t ubuntu-16-04 bash -c "apt -qq update;
                                               apt install -y git;
                                               apt install -y maven;
                                               apt install -y openjfx;
                                               apt install -y gettext"
      script:
        - docker exec -t ubuntu-16-04 bash -c "cd /travis;
                                               git clone https://github.com/PhoenicisOrg/phoenicis.git;
                                               cd phoenicis;
                                               mvn -B clean package"
      before_cache:
        - docker exec -t ubuntu-16-04 bash -c "cp /travis/phoenicis/phoenicis-dist/target/*.deb /travis/travis_cache/"
    # build + test
    - stage: Build + test
      name: Linux Oracle JDK 8
      os: linux
      dist: trusty
      jdk: oraclejdk8
      addons:
        apt:
          packages: oracle-java8-installer
    - stage: Build + test
      name: Linux OpenJDK 10
      os: linux
      dist: trusty
      jdk: openjdk10
    - stage: Build + test
      name: Linux OpenJDK 11
      os: linux
      dist: trusty
      jdk: openjdk11
    - stage: Build + test
      name: Linux OpenJDK 11 (Flatpak)
      os: linux
      dist: trusty
      jdk: openjdk11
      after_script:
        - cd phoenicis-dist/src/flatpak/
        - flatpak-builder build-dir org.phoenicis.javafx.json --force-clean
    - stage: Build + test
      name: Linux Oracle JDK 11
      os: linux
      dist: trusty
      jdk: oraclejdk11
    - stage: Build + test
      name: OSX XCode 9.2
      os: osx
      osx_image: xcode9.2

    # Install packages
    # .deb
    - stage: Install packages
      name: Install .deb
      os: linux
      dist: trusty
      jdk: openjdk8
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name ubuntu-16-04 -v $HOME:/travis ubuntu:16.04 tail -f /dev/null
      install:
        - docker exec -t ubuntu-16-04 bash -c "dpkg --add-architecture i386 && apt -qq update"
      script:
        # check that cache has been filled in current build
        - if test "$TRAVIS_BUILD_ID" != `cat $HOME/travis_cache/travis_build_id`; then travis_terminate 1; fi
        - rm -f $HOME/travis_cache/travis_build_id
        - docker exec -t ubuntu-16-04 bash -c "apt install -y /travis/travis_cache/*.deb"
        - mv $HOME/travis_cache $HOME/travis_cache_old
        - mkdir $HOME/travis_cache # clear the cache

    # Check GitHub Pages
    - stage: Check GitHub Pages
      env: NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
      language: ruby
      rvm:
        - 2.5
      before_install: cd docs
      script:
        - bundle exec jekyll build
        - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --assume-extension
