language: java
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

matrix:
  include:
    # Check the format
    - stage: Check format
      jdk: oraclejdk8
      os: linux
      dist: trusty
      install:
        # do not use default install (runs formatter)
        - mvn dependency:go-offline
      script:
        - mvn -Pcheck-formatted validate formatter:validate

    # The normal tests
    - stage: Build + test
      - jdk: oraclejdk8
        os: linux
        dist: trusty
      - jdk: oraclejdk9
        os: linux
        dist: trusty
      - os: osx
        osx_image: xcode9.2
