language: java

# avoid double builds on pull requests
branches:
  only:
    - master

jobs:
  include:
    # Check format
    - stage: Basics
      name: Check format
      # do not use default install (runs formatter)
      install: true
      script: mvn -Pcheck-formatted validate formatter:validate

    # build + test
    - stage: Build + test
      name: Linux OpenJDK 10
      os: linux
      dist: trusty
      jdk: openjdk10
      script: mvn clean package
    - stage: Build + test
      name: Linux OpenJDK 11
      os: linux
      dist: trusty
      jdk: openjdk11
    - stage: Build + test
      name: Linux Oracle JDK 11
      os: linux
      dist: trusty
      jdk: oraclejdk11
    # Build + test packages
    - stage: Packages
      name: Flatpak
      os: linux
      dist: xenial
      jdk: openjdk11
      before_install:
        - sudo add-apt-repository ppa:alexlarsson/flatpak -y
        - sudo apt-get update -q
        - sudo apt-get install -y flatpak flatpak-builder
      after_script:
        - flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        - flatpak --user -y install flathub org.freedesktop.Platform/x86_64/18.08
        - flatpak --user -y install flathub org.freedesktop.Sdk/x86_64/18.08
        - flatpak --user -y install flathub org.freedesktop.Sdk.Extension.openjdk11/x86_64/18.08
        - flatpak --user -y install flathub org.freedesktop.Platform.Compat.i386/x86_64/18.08
        - flatpak --user -y install flathub org.freedesktop.Platform.GL32.nvidia-410-73/x86_64/1.4
        - cd phoenicis-dist/src/flatpak/
        - flatpak-builder build-dir org.phoenicis.javafx.json --force-clean
    - stage: Packages
      name: deb
      os: linux
      dist: xenial
      jdk: openjdk11
      after_script:
        - mvn -B clean package
        - cd phoenicis-dist/src/scripts
        - bash phoenicis-create-package.sh
    - stage: Packages
      name: dmg
      os: osx
      osx_image: xcode10.1
      after_script:
        - mvn -B clean package
        - cd phoenicis-dist/src/scripts
        - bash phoenicis-create-package.sh

    # Check GitHub Pages
    - stage: Check GitHub Pages
      env: NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
      language: ruby
      rvm:
        - 2.5
      before_install: cd docs
      script:
        - bundle exec jekyll build
        - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --assume-extension
