sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      os: linux
    - language: java
      jdk: oraclejdk9
      os: linux
    - language: java
      jdk: openjdk8
      os: linux
    - language: java
      jdk: openjdk9
      os: linux
    - language: java
      os: osx

jobs:
  include:
    - stage: Check format
      script: ./check_formatted.sh
