language: java

dist: trusty
sudo: false

os:
- linux

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

jdk:
- oraclejdk8
- oraclejdk9
- openjdk8
- openjdk9

env:

matrix:
  include:
  - os: osx

jobs:
  include:
    - stage: Check format
      script: ./check_formatted.sh
