language: java

dist: trusty
sudo: false

os:
- linux
- osx

jdk:
- oraclejdk8
- oraclejdk9
- openjdk8
- openjdk9

env:

matrix:
  include:
  - jdk: oraclejdk8
    os: linux
    addons:
      apt:
        packages:
          - oracle-java8-installer
  - jdk: oraclejdk9
    os: linux
    addons:
      apt:
        packages:
          - oracle-java9-installer
  - jdk: openjdk8
    os: linux
  - jdk: openjdk9
    os: linux
  - os: osx

jobs:
  include:
    - stage: Check format
      script: ./check_formatted.sh
