title: Phoenicis Documentation
email:
description: >- 
  The documentation for Phoenicis.
baseurl: /POL-POM-5
url: https:///plata.github.io
minimal_mistakes_skin: dark

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
  
author:
  name   : "Phoenicis"
  avatar : "/assets/images/phoenicis.png"
  bio    : "The future of PlayOnLinux and PlayOnMac"
  uri    : "http://www.phoenicis.org/"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
