title: Phoenicis Documentation
email:
description: >- 
  The documentation for Phoenicis.
baseurl: /POL-POM-5
url: https://plata.github.io
minimal_mistakes_skin: contrast

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

search                   : true
search_full_content      : true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
  
author:
  name   : "Phoenicis"
  avatar : "/assets/images/phoenicis.png"
  bio    : "The future of PlayOnLinux and PlayOnMac"
  uri    : "http://www.phoenicis.org/"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"
