title: Phoenicis Documentation
email:
description: >- 
  The documentation for Phoenicis.
baseurl: /POL-POM-5
url: https:///plata.github.io
minimal_mistakes_skin: dark

remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
