title                    : Phoenicis Documentation
name                     : phoenicis.org
description              : The documentation for Phoenicis.
url                      : https://plata.github.io
baseurl                  : /POL-POM-5
repository               : plata/POL-POM-5

remote_theme             : mmistakes/minimal-mistakes
minimal_mistakes_skin    : contrast

markdown: kramdown
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

search                   : true
search_full_content      : true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  
author:
  name   : "Phoenicis"
  avatar : "/assets/images/phoenicis.png"
  bio    : "The future of PlayOnLinux and PlayOnMac"
  uri    : "http://www.phoenicis.org/"

include:
  - _docs
  - _pages

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
  
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"
  # _docs
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"
        
# HTML Compression
compress_html:
  clippings: all
