name: checkstyle

on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@0.3.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        level: error
        filter_mode: diff_context
        fail_on_error: true
        reporter: github-pr-review
